import {useEffect,useRef,useState,type ReactNode} from 'react';
import type {Alarm,DataState,Health,NetworkLink,NetworkNode,TrendPoint} from '../types';
import {clampPercent,formatMetric} from '../format';
export function Screen({children}:{children:ReactNode}){const [scale,setScale]=useState(1);useEffect(()=>{const resize=()=>setScale(Math.min(innerWidth/1920,innerHeight/1080));resize();addEventListener('resize',resize);return()=>removeEventListener('resize',resize)},[]);return <main className="screen" style={{transform:`translate(-50%,-50%) scale(${scale})`}}>{children}</main>}
export function KpiCard({label,value,unit,decimals=0,status='normal',description,updatedAt}:{label:string;value:number|null;unit?:string;decimals?:number;status?:Health;description?:string;updatedAt?:string}){return <article className={`kpi ${status}`}><span className="muted">{label}</span><strong>{formatMetric(value,decimals)} <small>{value!=null&&unit}</small></strong><span className="caption">{value==null?'暂无数据':description}{updatedAt&&` · ${updatedAt}`}</span></article>}
export function Panel({title,source,state='ready',onRetry,children}:{title:string;source?:string;state?:DataState;onRetry?:()=>void;children?:ReactNode}){return <section className="panel" aria-busy={state==='loading'}><header><h2>{title}</h2><span className="caption muted">{source}</span></header><div className="panel-body">{state==='empty'?<p className="muted">暂无数据，请调整时间或检查采集。</p>:<>{state!=='ready'&&<div role="status" className={`data-state ${state}`}>{({loading:'数据加载中…',error:'数据获取失败',stale:'数据已过期'} as Record<string,string>)[state]}{onRetry&&state==='error'&&<button onClick={onRetry}>重试</button>}</div>}{children}</>}</div></section>}
export function StatusBadge({status}:{status:Health}){return <span className={`badge ${status}`}>{({normal:'● 正常',warning:'▲ 重要',critical:'! 严重'})[status]}</span>}
export function LayerTabs<T extends string>({items,value,onChange}:{items:readonly {id:T;label:string;disabled?:boolean}[];value:T;onChange:(id:T)=>void}){return <div className="tabs" role="group" aria-label="网络图层">{items.map(i=><button key={i.id} disabled={i.disabled} aria-pressed={value===i.id} className={value===i.id?'selected':''} onClick={()=>onChange(i.id)}>{i.label}</button>)}</div>}
export function AlarmList({alarms,onSelect}:{alarms:Alarm[];onSelect:(a:Alarm)=>void}){const [paused,setPaused]=useState(false);const container=useRef<HTMLDivElement>(null);const hovered=useRef(false);useEffect(()=>{if(paused)return;const t=setInterval(()=>{const el=container.current;if(el&&!hovered.current&&!matchMedia('(prefers-reduced-motion: reduce)').matches){if(el.scrollTop+el.clientHeight>=el.scrollHeight-1)el.scrollTop=0;else el.scrollTop+=1;}},80);return()=>clearInterval(t)},[paused]);return <><button className="pause" aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?'继续滚动':'暂停滚动'}</button><div ref={container} className="alarm-list" onMouseEnter={()=>{hovered.current=true}} onMouseLeave={()=>{hovered.current=false}} onFocus={()=>{hovered.current=true}} onBlur={()=>{hovered.current=false}}>{alarms.map(a=><button className="alarm" key={a.id} onClick={()=>onSelect(a)}><span className="caption muted">{a.time}</span><span className={`badge ${a.severity}`}>{({critical:'! 严重',warning:'▲ 重要',info:'● 提示'})[a.severity]}</span><span>{a.message}</span><span className="caption muted">{a.recovered?'已恢复':'未恢复'} · {({pending:'待处理',processing:'处理中',closed:'已关闭'})[a.processStatus]}</span></button>)}</div></>}
export function DetailCard({title,rows,onClose}:{title:string;rows:{label:string;value:ReactNode}[];onClose:()=>void}){return <aside className="detail" aria-label="资源详情"><header><h3>{title}</h3><button onClick={onClose} aria-label="关闭详情">×</button></header>{rows.map(r=><div className="detail-row" key={r.label}><span className="muted">{r.label}</span><strong>{r.value}</strong></div>)}</aside>}
export function ProgressRow({label,value,total=100,unit='%',status='normal'}:{label:string;value:number;total?:number;unit?:string;status?:Health}){const percent=total>0?clampPercent(value/total*100):0;return <div className="progress-row"><span>{label}</span><strong>{formatMetric(value)} {unit}</strong><div className="track"><i className={status} style={{width:`${percent}%`}}/></div></div>}
export function Gauge({value,label}:{value:number|null;label:string}){const pct=value==null?0:clampPercent(value);return <div className="gauge"><svg viewBox="0 0 240 140" role="img" aria-label={`${label} ${formatMetric(value,1)}%`}><path d="M20 120A100 100 0 0 1 220 120" pathLength="100" className="gauge-track"/><path d="M20 120A100 100 0 0 1 220 120" pathLength="100" strokeDasharray={`${pct} 100`} className="gauge-value"/><text x="120" y="96" textAnchor="middle">{formatMetric(value,1)}{value!=null?'%':''}</text><text className="gauge-label" x="120" y="122" textAnchor="middle">{label}</text></svg></div>}
export function TrendChart({points,unit}:{points:TrendPoint[];unit:string}){const values=points.flatMap(p=>[p.current,p.previous]).filter((n):n is number=>n!=null&&Number.isFinite(n));const max=Math.max(1,...values);const path=(key:'current'|'previous')=>{let pen=false;return points.map((p,i)=>{const v=p[key];if(v==null||!Number.isFinite(v)){pen=false;return ''}const command=pen?'L':'M';pen=true;return `${command}${30+i*420/Math.max(1,points.length-1)} ${135-v/max*105}`}).join(' ')};return <svg className="trend-chart" viewBox="0 0 480 165" role="img" aria-label={`出口流量趋势，单位${unit}`}><text x="30" y="15">{unit}</text>{[30,65,100,135].map(y=><g key={y}><path className="chart-grid" d={`M30 ${y}H450`}/><text x="0" y={y+4}>{(max*(135-y)/105).toFixed(1)}</text></g>)}<path d={path('previous')} className="previous"/><path d={path('current')} className="current"/>{points.map((p,i)=><g key={p.time}><circle cx={30+i*420/Math.max(1,points.length-1)} cy={p.current==null?135:135-p.current/max*105} r="8" fill="transparent"><title>{`${p.time}：今日 ${formatMetric(p.current,2)} / 昨日 ${formatMetric(p.previous,2)} ${unit}`}</title></circle>{(i===0||i===points.length-1)&&<text x={30+i*420/Math.max(1,points.length-1)} y="158" textAnchor="middle">{p.time}</text>}</g>)}</svg>}
export function Topology({nodes,links,selectedId,onSelect}:{nodes:NetworkNode[];links:NetworkLink[];selectedId?:string;onSelect:(n:NetworkNode)=>void}){const byId=new Map(nodes.map(n=>[n.id,n]));return <svg className="topology" viewBox="0 0 900 440" aria-label="城域网络拓扑">{links.map(l=>{const a=byId.get(l.source),b=byId.get(l.target);return a&&b?<line key={l.id} className={`link ${l.status}`} x1={a.x} y1={a.y} x2={b.x} y2={b.y}/>:null})}{nodes.map(n=><g key={n.id} role="button" tabIndex={0} aria-label={`${n.name} ${n.status}`} aria-pressed={selectedId===n.id} onClick={()=>onSelect(n)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(n)}}} className={`node ${n.status} ${selectedId===n.id?'active':''}`} transform={`translate(${n.x},${n.y})`}>{n.type==='access'?<circle r="20"/>:<rect x="-24" y="-18" width="48" height="36" rx="4"/>}<text y="42" textAnchor="middle">{n.status==='critical'?'! ':''}{n.name}</text></g>)}</svg>}
export function EventTicker({events}:{events:string[]}){const [paused,setPaused]=useState(false);return <footer className="ticker"><strong>实时事件</strong><button aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?'继续':'暂停'}</button><div className="ticker-window"><div className={paused?'ticker-track paused':'ticker-track'}>{events.map((e,i)=><span key={i}>{e}</span>)}</div></div></footer>}
